/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Semordnilap;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
    System.out.println("Welcome to Semordnilap. Please enter a word:");
    if(isPalindrome(readString())) {
        System.out.println("That's a palindrome!");
    } else {
        System.out.println("That's not a palindrome...");
    }
    }

    private static String readString() {
        Scanner scanner = new Scanner(System.in);
        return scanner.nextLine();
    }

    private static boolean isPalindrome(String string) {
        String reverse = new StringBuilder(string).reverse().toString();
        if(reverse.equalsIgnoreCase(string)) {
            return true;
        } else {
            return false;
        }
    }
}
