/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Semordnilap;

import java.util.Scanner;

public class App {

    public static final String welcome = "Welcome to Semordnilap. Please enter a word:";

    public static void main(String[] args) {
        boolean doContinue = true;
        while (doContinue) {
            System.out.println(welcome);
            Determine determine = new Determine();
            System.out.println(determine.isPalindromeOrSemordnilap(readString()));
        }
    }

    private static String readString() {
        Scanner scanner = new Scanner(System.in);
        return scanner.nextLine();
    }
}
