/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Semordnilap;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest;
    public void setUp() {
        classUnderTest = new App();
    }
    @Test public void testAppIsAPalindrome() {
        assertTrue(classUnderTest.isPalindromeOrSemordnilap("bob"));
    }

    @Test public void testAppIsNotAPalindrome() {
        assertTrue(!classUnderTest.isPalindromeOrSemordnilap("Fill"));
    }
}
