/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Semordnilap;

import org.junit.Before;
import org.junit.Test;

import javax.net.ssl.HttpsURLConnection;
import java.io.IOException;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class DetermineTest {
    public HttpsURLConnection mockUrlConn = mock(HttpsURLConnection.class);
    Determine classUnderTest;

    @Before
    public void setUp() {
        classUnderTest = new Determine();
    }

    @Test public void testAppIsAPalindrome() throws IOException {
        when(mockUrlConn.getResponseCode()).thenReturn(200);
        assertEquals("That's a palindrome!", classUnderTest.isPalindromeOrSemordnilap("bob"));
    }

    @Test public void testAppIsNotAPalindrome() throws IOException {
        when(mockUrlConn.getResponseCode()).thenReturn(404);
        assertEquals("That's not a palindrome or semordnilap...", classUnderTest.isPalindromeOrSemordnilap("Cool"));
    }

    @Test public void testAppIsASemordnilap() throws IOException {
        when(mockUrlConn.getResponseCode()).thenReturn(200);
        assertEquals("That's a semordnilap!", classUnderTest.isPalindromeOrSemordnilap("yob"));
    }
}
